tracker/accounts/urls.py
from . import views
from django.conf.urls import url
from django.conf.urls import url, include
import accounts.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    url(r'^logout/', views.logoutview, name='logout'),
    url(r'^home/', views.homeview, name='home'),
    url(r'^forgot/', views.forgotview, name='forgot'),
    url(r'^usercreated/', views.usercreatedview, name='usercreated'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^password_changed/$', views.password_changed, name='password_changed'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/posts/urls.py
from . import views
from django.conf.urls import url
from urllib.parse import unquote
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name = 'posts'

urlpatterns = [
    url(r'^quicklinks/', views.quicklinkview, name='quicklinks'),
    url(r'^tracker_list/', views.tracker_list, name='tracker_list'),
    url(r'^(?P<track_id>[0-9]+)/$', views.tracker_view, name="tracker_view"),
    url(r'^tracker_edit/', views.tracker_edit, {}, name='tracker_edit'),
    url(r'^modify/(?P<track_id>[0-9]+)/$', views.tracker_edit, {}, name='modify'),
    url(r'^search/$', views.search, name='search'),
    url(r'^pending/', views.pending, name='pending'),
    url(r'^unattended/', views.unattended, name='unattended'),
    url(r'^schedule/', views.schedule, name='schedule'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/tracker/urls.py
from django.contrib import admin
from django.conf.urls import url, include
import accounts.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import *
from accounts import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^updates/', include('updates.urls')),
    #url(r'^devops/', include('devops.urls')),
    url(r'^$', views.loginview, name="login")
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/updates/urls.py
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'updates'

urlpatterns = [
    url(r'^modify/(?P<up_id>[0-9]+)/$', views.process_updates, {}, name='modify'),
    url(r'^process_updates/', views.process_updates, {}, name='process_updates'),
    url(r'^updates_list/', views.updates_list, name='updates_list'),
    url(r'^(?P<up_id>[0-9]+)/$', views.update_view, name="update_view"),
]

tracker/templates/base.html
<!DOCTYPE html>
<html>
<head>
{% csrf_token %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

.navbar {
  overflow: hidden;
  background-color: #2C9FDD;
  text-decoration: none;
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.dropdowns {
  float: right;
  overflow: hidden;
}

.dropdowns .dropbtns {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
  float: right;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: #56B2E4;
}
.navbar a:hover, .dropdowns:hover .dropbtns {
  background-color: #56B2E4;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #2C9FDD;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: white;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #56B2E4;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.dropdowns:hover .dropdown-content {
  display: block;
}

</style>
</head>
<body>
<div class="container">
<div class="navbar">
  <a href="{% url 'accounts:home' %}">Home</a>
  <a href="{% url 'updates:updates_list' %}">Process Updates</a>
  <a href="{% url 'posts:schedule' %}">Engineer Schedule</a>
  <a href="{% url 'posts:quicklinks' %}">Quick Links</a>


  <div class="dropdown">
    <button class="dropbtn">Non PD alerts
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'posts:tracker_list' %}" >Tracker</a>
      <a href="http://imeasure.iopex.com/posts/pending/?Status=pending">Pending Tickets</a>
      <a href="http://imeasure.iopex.com/posts/unattended/?Resolved_by_Engineer=noc">Unattended Tickets</a>
    </div>
  </div>



  <div class="dropdowns">
    <button class="dropbtns">{{ user.get_full_name }}<i class="fa fa-caret-down"></i></button>
    <div class="dropdown-content">
      <a href="{% url 'accounts:change_password' %}" style="font-size:95%;">Change Password</a>
      <a href="#" onClick="document.getElementById('logout').submit()">Logout</a>
    </div>
    </div>

      <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
        <input type="hidden">
      </form>
</div>
</body>
{% block content %}
{% endblock %}
</html>