tracker/accounts/urls.py
from . import views
from django.conf.urls import url
from django.conf.urls import url, include
import accounts.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    url(r'^logout/', views.logoutview, name='logout'),
    url(r'^home/', views.homeview, name='home'),
    url(r'^forgot/', views.forgotview, name='forgot'),
    url(r'^usercreated/', views.usercreatedview, name='usercreated'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^password_changed/$', views.password_changed, name='password_changed'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/posts/urls.py
from . import views
from django.conf.urls import url
from urllib.parse import unquote
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name = 'posts'

urlpatterns = [
    url(r'^quicklinks/', views.quicklinkview, name='quicklinks'),
    url(r'^tracker_list/', views.tracker_list, name='tracker_list'),
    url(r'^(?P<track_id>[0-9]+)/$', views.tracker_view, name="tracker_view"),
    url(r'^tracker_edit/', views.tracker_edit, {}, name='tracker_edit'),
    url(r'^modify/(?P<track_id>[0-9]+)/$', views.tracker_edit, {}, name='modify'),
    url(r'^search/$', views.search, name='search'),
    url(r'^pending/', views.pending, name='pending'),
    url(r'^unattended/', views.unattended, name='unattended'),
    url(r'^schedule/', views.schedule, name='schedule'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/tracker/urls.py
from django.contrib import admin
from django.conf.urls import url, include
import accounts.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import *
from accounts import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^updates/', include('updates.urls')),
    #url(r'^devops/', include('devops.urls')),
    url(r'^$', views.loginview, name="login")
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/updates/urls.py
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'updates'

urlpatterns = [
    url(r'^modify/(?P<up_id>[0-9]+)/$', views.process_updates, {}, name='modify'),
    url(r'^process_updates/', views.process_updates, {}, name='process_updates'),
    url(r'^updates_list/', views.updates_list, name='updates_list'),
    url(r'^(?P<up_id>[0-9]+)/$', views.update_view, name="update_view"),
]

tracker/posts/models.py
from django.db import models
import datetime
from django.utils.translation import gettext as _
from datetime import date
from datetime import timedelta as tdelta
from django.utils import timezone
import calendar


# Create your models here.
class Post(models.Model):
    today = datetime.date.today()
    years = today.year
    Year = models.PositiveSmallIntegerField(blank=False, null=False, db_column='yeer',default=years)

    weeknumbers = date.today().isocalendar()[1]
    weeknumber = "Week {}".format(weeknumbers)
    Week = models.CharField(max_length=20, blank=False, null=True, db_column='weekno',default=weeknumber)

    today = datetime.date.today()
    x=calendar.month_name[today.month]
    Month = models.CharField(max_length=100, null=False, blank=False, db_column='menth',default=x)
    #Date = models.DateField(_("Date"), default=datetime.date.today, null=False, blank=False, db_column='dete')

    #inidate=timezone.now().date()
    inidate=datetime.date.today().strftime('%Y-%m-%d')
    Date = models.DateField(null=False, blank=False, db_column='dete',default=inidate)


    curtime = datetime.datetime.now()
    currenttime = curtime.hour
    if currenttime in (8,9,10,11,12,13,14,15):
        y = "APAC"
    elif currenttime in (16,17,18,19,20,21,22):
        y = "EMEA"
    else:
        y = "USA"
    Shift = models.TextField(null=False, db_column='shyft', default=y)

    weekno = datetime.datetime.today().weekday()
    if weekno < 5:
        x = ("Weekday")
    else:
        x = ("Weekend")
    Day_Of_Week = models.TextField(null=False, db_column='dayofweek', default=x)
    Start_Time = models.CharField(max_length=8,blank=False,null=True,db_column='stime')
    Responded_Time =  models.CharField(max_length=8,blank=False,null=True,db_column='rtime')
    Time_spent = models.CharField(max_length=8,blank=False,null=True, db_column='wtime')
    Responsible_Team = models.CharField(max_length=100, null=True, blank=False, default='Please select', db_column='respteam')
    False_Alarm = models.TextField(null=False, db_column='falsealarm',default="No")
    Incident_Type = models.CharField(max_length=100, null=True, blank=False, default='Please select', db_column='itype')
    Priority = models.CharField(max_length=10 ,null=False, db_column='priority', default='None')
    General_Health_Check = models.CharField(max_length=100, null=True, blank=True, default='NA', db_column='ghcname')
    Alert = models.CharField(max_length=100, null=True, blank=True, default='NA', db_column='alertname')
    Task = models.CharField(max_length=100, null=True, blank=True, default='NA', db_column='taskname')
    If_Others_Please_Specify = models.CharField(max_length=100, null=False, blank=True, db_column='others', default='NA')
    Description = models.TextField(null=True, blank=False, db_column='descrp')
    Environment = models.CharField(max_length=100, null=True, blank=False, default='Please select', db_column='env')
    Host_Type = models.CharField(max_length=100, null=True, blank=False, default='Please select', db_column='hostype')
    Host_Name = models.CharField(max_length=100, null=True, blank=False, db_column='hostname')
    Source_of_Alert = models.CharField(max_length=100, null=True, blank=False, default='Please select', db_column='source')
    Mode_of_Alert = models.TextField(null=False, db_column='mode', default="Manual")
    NOC_Engineer = models.CharField(max_length=100, null=True, blank=False, default='Please select', db_column='engineer')
    Remediation = models.TextField(null=True, blank=True, default='NA', db_column='remediation',)
    Escalated = models.CharField(max_length=100, null=False, blank=False, default='No', db_column='escalated')
    Escalated_Reason = models.CharField(max_length=100, null=True, blank=True, default='NA', db_column='escreason')
    Status = models.CharField(max_length=100, null=True, blank=True, default='Resolved', db_column='status')
    Escalated_to = models.CharField(max_length=100, null=True, blank=True, default='NA', db_column='escalatedto')
    Resolved_by_Team = models.CharField(max_length=100, null=True, blank=False, default='Please select', db_column='resolvedteam')
    Resolved_by_Engineer = models.CharField(max_length=30, null=False, default='noc', db_column='resolvedby')
    Resolution = models.TextField(null=True, blank=False, db_column='resolution')
    Comments = models.TextField(null=True, blank=False, db_column='comments')
    #Interval = models.IntegerField(blank=True, null=False, db_column='intrval')
    #Complexity = models.TextField(blank=True, null=False, db_column='cmplx')

class Schedules(models.Model):
    title = models.CharField(max_length = 200, null=True)
    image = models.ImageField(upload_to='media/')

tracker/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse, render_to_response
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from . import forms
from .models import Post
from .forms import CreateArticle
from django.http import HttpResponse
from django.contrib.auth.forms import UserChangeForm
from .tables import TrackerTable
from django_tables2 import RequestConfig
from .filters import TrackerFilter
from .filters import PendingFilter
from django_tables2.export.export import TableExport
from .models import Schedules
from .filters import UnattendedFilter

@login_required
def quicklinkview(request):
    return render(request, 'posts/quicklinks.html')

#def tracker_list(request):
#    tracks = Post.objects.all()
#    return render(request,'posts/tracker_list.html',{'tracks':tracks})
@login_required
def tracker_list(request):
    table = TrackerTable(Post.objects.all(), order_by="-id")
    #filter = AFilter(request.GET, queryset=table)
    RequestConfig(request, paginate={'per_page': 100}).configure(table)
    export_format = request.GET.get('_export', None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, table, exclude_columns=('editable','selection'))
        return exporter.response('table.{}'.format(export_format))

    return render(request, 'posts/tracker_list.html', {'table': table})

@login_required
def tracker_view(request, track_id):
    #post = Post.objects.get(pk=post_id)
    track = get_object_or_404(Post, pk=track_id)
    return render(request, 'posts/tracker_view.html', {'track':track})

@login_required
def tracker_edit(request, track_id=None, template_name='posts/tracker_edit.html'):
    if track_id is not None:
        track = get_object_or_404(Post, pk=track_id)
    else:
        track = Post()
    tracker = CreateArticle(request.POST or None, instance=track)
    if request.POST and tracker.is_valid():
        tracker.save()
        redirect_url = reverse('posts:tracker_list')
        return redirect(redirect_url)

    return render(request, template_name, {
        'tracker': tracker
    })

@login_required
def search(request):
    tracker_list = Post.objects.all()
    tracker_filter = TrackerFilter(request.GET, queryset=tracker_list)
    return render(request, 'posts/search.html', {'filter': tracker_filter})

@login_required
def pending(request):
    pending_list = Post.objects.all()
    pending_filter = PendingFilter(request.GET, queryset=pending_list)
    return render(request, 'posts/pending.html', {'filter': pending_filter})

@login_required
def schedule(request):
    schedules = Schedules.objects.all()
    return render(request, 'posts/engschedule.html', {'schedules':schedules})

@login_required
def unattended(request):
    unattended_list = Post.objects.all()
    unattended_filter = UnattendedFilter(request.GET, queryset=unattended_list)
    return render(request, 'posts/unattended.html', {'filter': unattended_filter})




























'''
def tracker_edit(request):
    if request.method == 'POST':
        tracker = forms.CreateArticle(request.POST)
        if tracker.is_valid():
            #save article to db
            tracker.save()
            return redirect('posts:tracker_list')
    else:
        tracker = forms.CreateArticle()
    return render(request, 'posts/tracker_edit.html',{'tracker':tracker})

def tracker_list(request, track_id=None):
    if request.method == 'POST':
        pks = request.POST.getlist("selection")
        table = TrackerTable(Post.objects.filter(pk__in=pks))
    else:
        table = TrackerTable(Post.objects.all(), order_by="-id")
        #filter = AFilter(request.GET, queryset=table)
    RequestConfig(request).configure(table)
    export_format = request.GET.get('_export', None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, table, exclude_columns=('editable','selection'))
        return exporter.response('table.{}'.format(export_format))

    return render(request, 'posts/tracker_list.html', {'table': table})


def tracker_list(request):
    table = TrackerTable(Post.objects.all(), order_by="-id")
    #filter = AFilter(request.GET, queryset=table)
    RequestConfig(request).configure(table)
    export_format = request.GET.get('_export', None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, table, exclude_columns=('editable','selection'))
        return exporter.response('table.{}'.format(export_format))

    return render(request, 'posts/tracker_list.html', {'table': table})
'''

tracker/posts/templates/posts/pending.html
{% extends 'base.html' %}

{% block content %}
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Pending</title>
</head>
<style>
  th {
    text-align: left;
    background-color: #56B2E4;
    color: #FFFFFF;
    text-decoration: none!important;
    text-align: left;
    padding: 8px;
    font-size: 80%;
  }

  table {
  border-collapse: collapse;
  width: 100%;
  }

  td {
    text-align: left;
    padding: 8px;
    font-size: 80%;
  }

  tr:hover {background-color:#CBE3FA;}

  tr:nth-child(even) {background-color: #F2F9FD;}

  .buttons {
    background-color: #2C9FDD;
    border-style: solid;
    color: white;
    padding: 7px 12px;
    text-align: center;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }

  .buttons:hover {
    background-color: #4C596B;
  }

  div.table-container {
    display: inline-block;
    position:relative;
    overflow:auto;
  }

</style>
  <ul>
    <div style="background: white;
    width: 100%;
    height: 100%;
    overflow: scroll;
    border: 2px solid #2C9FDD;">
    <table style="width:100%">
      <tr>
        <th>Ticket number</th>
        <th>Year</th>
        <th>Month</th>
        <th>Date</th>
        <th>Shift</th>
        <th>Day Of Week</th>
        <th>Time</th>
        <th>Responded Time</th>
        <th>Time spent</th>
        <th>Complexity</th>
        <th>Responsible Team</th>
        <th>False alarm</th>
        <th>Incident Type</th>
        <th>Priority</th>
        <th>If Others Please Specify</th>
        <th>Description</th>
        <th>Environment</th>
        <th>Host Type</th>
        <th>Host Name</th>
        <th>Source of Alert</th>
        <th>Mode of Alert</th>
        <th>NOC Engineer</th>
        <th>Remediation</th>
        <th>Escalated</th>
        <th>Escalated Reason</th>
        <th>Status</th>
        <th>Escalated to</th>
        <th>Resolved by Team</th>
        <th>Resolved by Engineer</th>
        <th>Resolution</th>
        <th>Comments</th>
      </tr>
  {% for filter in filter.qs %}
  <tr>
    <td><a  href="{% url 'posts:tracker_view' filter.id %}">{{ filter.id }}</a></td>
    <td>{{ filter.Year }}</td>
    <td>{{ filter.Month }}</td>
    <td>{{ filter.Date }}</td>
    <td>{{ filter.Shift }}</td>
    <td>{{ filter.Day_Of_Week }}</td>
    <td>{{ filter.Time }}</td>
    <td>{{ filter.Responded_Time }}</td>
    <td>{{ filter.Time_spent }}</td>
    <td>{{ filter.Complexity }}</td>
    <td>{{ filter.Responsible_Team }}</td>
    <td>{{ filter.False_alarm }}</td>
    <td>{{ filter.Incident_Type }}</td>
    <td>{{ filter.Priority }}</td>
    <td>{{ filter.If_Others_Please_Specify }}</td>
    <td>{{ filter.Description }}</td>
    <td>{{ filter.Environment }}</td>
    <td>{{ filter.Host_Type }}</td>
    <td>{{ filter.Host_Name }}</td>
    <td>{{ filter.Source_of_Alert }}</td>
    <td>{{ filter.Mode_of_Alert }}</td>
    <td>{{ filter.NOC_Engineer }}</td>
    <td>{{ filter.Remediation }}</td>
    <td>{{ filter.Escalated }}</td>
    <td>{{ filter.Escalated_Reason }}</td>
    <td>{{ filter.Status }}</td>
    <td>{{ filter.Escalated_to }}</td>
    <td>{{ filter.Resolved_by_Team }}</td>
    <td>{{ filter.Resolved_by_Engineer }}</td>
    <td>{{ filter.Resolution }}</td>
    <td>{{ filter.Comments }}</td>
  </tr>
  {% endfor %}
</div>
  </ul>
  {% csrf_token %}
{% endblock %}

tracker/posts/templates/posts/processupdates.html
{% extends 'base.html' %}


{% block content %}
<html>
<body>
<p>prupdates</p>
</body>
</html>
{% endblock %}

tracker/posts/templates/posts/tracker_edit.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="{% static 'js/toggle.js' %}"></script>
  <script src="{% static 'js/inctoggle.js' %}"></script>
  <script src="{% static 'js/pchild.js' %}"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script>
        $( function() {
            $( "#id_Date" ).datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true
            });
        });
</script>
  <title>Add new!</title>
  <script>
  function updateText(type)
   {
 var id = type+'Text';
 document.getElementById(id).value = document.getElementById(type).value;
   }
</script>

  <script>
  $(document).ready(function () {
      toggleFieldss();
      $("#id_Incident_Type").change(function () {
          toggleFieldss();
      });

  });

  function toggleFieldss() {
      if ($("#id_Incident_Type").val() === "Alert")
          $("#id_Alert").show() && $("#id_Task").hide() && $("#id_General_Health_Check").hide() && $("#id_If_Others_Please_Specify").hide() && $('label[for=id_Alert], input#id_Alert').show() && $('label[for=id_Task], input#id_Task').hide()  && $('label[for=id_General_Health_Check], input#id_General_Health_Check').hide()
          && $('label[for=id_If_Others_Please_Specify], input#id_If_Others_Please_Specify').hide() ;


      else if ($("#id_Incident_Type").val() === "Task")
          $("#id_Alert").hide() && $("#id_Task").show() && $("#id_General_Health_Check").hide() && $("#id_If_Others_Please_Specify").hide() && $("#id_Remediation").hide() && $('label[for=id_Alert], input#id_Alert').hide() && $('label[for=id_Task], input#id_Task').show()  && $('label[for=id_General_Health_Check], input#id_General_Health_Check').hide()
          && $('label[for=id_If_Others_Please_Specify], input#id_If_Others_Please_Specify').hide() && $('label[for=id_Remediation], input#id_Remediation').hide() ;


      else if ($("#id_Incident_Type").val() === "GHC")
          $("#id_Alert").hide() && $("#id_Task").hide() && $("#id_General_Health_Check").show() && $("#id_If_Others_Please_Specify").hide() && $("#id_Remediation").hide() && $('label[for=id_Alert], input#id_Alert').hide() && $('label[for=id_Task], input#id_Task').hide()  && $('label[for=id_General_Health_Check], input#id_General_Health_Check').show()
          && $('label[for=id_If_Others_Please_Specify], input#id_If_Others_Please_Specify').hide() && $('label[for=id_Remediation], input#id_Remediation').hide() ;


      else if ($("#id_Incident_Type").val() === "Other")
          $("#id_Alert").hide() && $("#id_Task").hide() && $("#id_General_Health_Check").hide() && $("#id_If_Others_Please_Specify").show() && $("#id_Remediation").hide() && $('label[for=id_Alert], input#id_Alert').hide() && $('label[for=id_Task], input#id_Task').hide()  && $('label[for=id_General_Health_Check], input#id_General_Health_Check').hide()
          && $('label[for=id_If_Others_Please_Specify], input#id_If_Others_Please_Specify').show() && $('label[for=id_Remediation], input#id_Remediation').hide() ;
      }

  </script>
<script>
$(document).ready(function () {
    toggleFields();
    $("#id_Escalated").change(function () {
        toggleFields();
    });

});

function toggleFields() {
    if ($("#id_Escalated").val() === "Yes")
        $("#id_Escalated_to").show() && $("#id_Escalated_Reason").show() && $('label[for=id_Escalated_to], input#id_Escalated_to').show() && $('label[for=id_Escalated_Reason], input#id_Escalated_Reason').show();
    else
        $("#id_Escalated_to").hide() && $("#id_Escalated_Reason").hide() && $('label[for=id_Escalated_to], input#id_Escalated_to').hide() && $('label[for=id_Escalated_Reason], input#id_Escalated_Reason').hide();
}
</script>
</head>
<style>
* {
  box-sizing: border-box;
}

input[type=text], select, textarea {
  width: 300%;
  padding: 4px;
  border: 1px solid #4C596B;
  border-radius: 4px;
  resize: vertical;
}

label {
  padding: 1px 12px 12px 0;
  display: inline-block;
  margin-left: -80px;
}

input[type=submit] {
  background-color: white;
  color: #2C9FDD;
  padding: 3px 10px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: left;
  margin-left : 1%
}

input[type=reset] {
  background-color: white;
  color: #2C9FDD;
  padding: 3px 10px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: left;
  margin-left : 7%
}

input[type=submit]:hover {
  background-color: #4C596B;
}

input[type=reset]:hover {
  background-color: #4C596B;
}


/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

.border {
  background-color: #EAF5FB;
  width: 600px;
  border: 10px solid #56B2E4;
  padding: 2px;
  margin: 20px;
  margin-left: 400px;
}

.boxhead a {
    color: #2C9FDD;
    text-decoration: none;
}

.boxhead a:hover{
  background-color: #4C596B;
}

form {
        margin-left : 27%
    }

.inlineLabels ul {
  list-style:none;
}

form, fieldset{
  width:100%;
}

fieldset{
  border: 0 none;
  display: flex;
  padding: 5px 0;
  margin: 0;
}


label{
  width: 125px;
  white-space: pre-wrap;
  overflow: visible;
}

input{
  flex: 0 2 0;
}

ul#shiftid li{
 display: inline-block;
 width: 1px;
 margin-left: 89px;
 margin: -90px 0 0px 90px;
 clear: none;
 }

ul#weekid li{
 display: inline-block;
 width: 1px;
 margin-left: 89px;
 margin: -90px 0 0px 90px;
 }

ul#falseid li{
 display: inline-block;
 width: 1px;
 margin-left: 89px;
 margin: -90px 0 20px 90px;
 }

ul#modeid li{
 display: inline-block;
 width: 1px;
 margin-left: 89px;
 margin: -90px 0 20px 90px;
 }

ul#priorityid li{
 display: inline-block;
 width: 0%;
 margin-left: 89px;
 margin: -90px 0 20px 90px;
 }
 #mySidenav a {
   position: absolute;
   left: -80px;
   transition: 0.3s;
   padding: 15px;
   width: 100px;
   text-decoration: none;
   font-size: 20px;
   color: white;
   border-radius: 0 5px 5px 0;
 }

 #mySidenav a:hover {
   left: 0;
 }

 #home {
   top: 20px;
   background-color: #4CAF50;
 }

 #updates {
   top: 80px;
   background-color: #2196F3;
 }

 #schedule {
   top: 140px;
   background-color: #f44336;
 }

 #quicklinks {
   top: 200px;
   background-color: #555
 }
</style>

<body>
  <div id="mySidenav" class="sidenav">
    <a href="{% url 'accounts:home' %}" id="home">Home</a>
    <a href="{% url 'updates:updates_list' %}" id="updates">Updates</a>
    <a href="{% url 'posts:schedule' %}" id="schedule", style='font-size:16px';>Schedule</a>
    <a href="{% url 'posts:quicklinks' %}" id="quicklinks">Quick Links</a>
  </div>


<div class="border">
<form class="site-form" method="post" enctype="multipart/form-data">
  <fieldset>
  <div class="inlineLabels">
  {% csrf_token %}
    {{ tracker.as_p }}
  </div>
  </fieldset>
  <div class="boxhead">
    <input type="submit" value="Submit">&nbsp;
      <input type="reset" value="Reset">&nbsp;
    <button><a href="{% url 'posts:tracker_list' %}">Back to list</a></button>
  </div>

</form>
</div>

</body>
</html>

tracker/posts/templates/posts/tracker_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load bootstrap3 %}
{% load querystring from django_tables2 %}

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Tracker</title>
  {% csrf_token %}
<style>
  th {
    text-align: left;
    background-color: #56B2E4;
    color: #FFFFFF;
    text-decoration: none!important;
    text-align: left;
    padding: 8px;
    font-size: 80%;
  }

  table {
  border-collapse: collapse;
  width: 100%;
  }

  td {
    text-align: left;
    padding: 8px;
    font-size: 80%;
  }

  tr:hover {background-color:#CBE3FA;}

  tr:nth-child(even) {background-color: #F2F9FD;}

  .buttons {
    background-color: #2C9FDD;
    border-style: solid;
    color: white;
    padding: 7px 12px;
    text-align: center;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }

  .buttons:hover {
    background-color: #4C596B;
  }

  div.table-container {
    display: inline-block;
    position:relative;
    overflow:auto;
  }

  input {
  float: right;
  }

  input[type=text] {
    width: 130px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 10px;
    background-color: white;
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 6px 10px 8px 20px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
  }

  input[type=text]:focus {
    width: 100%;
  }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

</head>

<body>
 <form>
  <button class="buttons" formaction="{% url 'posts:search' %}">Advanced Search</button>
  <button class="buttons" formaction="{% url 'posts:tracker_edit' %}">Add New!</button>
  <div class="dropdown">
    <button class="buttons">Export
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% querystring '_export'='csv' %}">Download CSV</a>
      <a href="{% querystring '_export'='xls' %}">Download Excel</a>
      <a href="{% querystring '_export'='json' %}">Download JSON</a>
    </div>
  </div>
  <input id="myInput" type="text" placeholder="Search">
<div style="background: white;
width: 100%;
height: 100%;
overflow: scroll;
border: 2px solid #2C9FDD;
border-bottom: none;">

<table class="table table-striped">

<tbody  {{ table.attrs.tbody.as_html }} id="myTable">
    {% render_table table %}
</tbody>

</table>
</div>
  </form>
</body>

</html>
{% endblock %}