tracker/accounts/urls.py
from . import views
from django.conf.urls import url
from django.conf.urls import url, include
import accounts.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    url(r'^logout/', views.logoutview, name='logout'),
    url(r'^home/', views.homeview, name='home'),
    url(r'^forgot/', views.forgotview, name='forgot'),
    url(r'^usercreated/', views.usercreatedview, name='usercreated'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^password_changed/$', views.password_changed, name='password_changed'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/posts/urls.py
from . import views
from django.conf.urls import url
from urllib.parse import unquote
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name = 'posts'

urlpatterns = [
    url(r'^quicklinks/', views.quicklinkview, name='quicklinks'),
    url(r'^tracker_list/', views.tracker_list, name='tracker_list'),
    url(r'^(?P<track_id>[0-9]+)/$', views.tracker_view, name="tracker_view"),
    url(r'^tracker_edit/', views.tracker_edit, {}, name='tracker_edit'),
    url(r'^modify/(?P<track_id>[0-9]+)/$', views.tracker_edit, {}, name='modify'),
    url(r'^search/$', views.search, name='search'),
    url(r'^pending/', views.pending, name='pending'),
    url(r'^unattended/', views.unattended, name='unattended'),
    url(r'^schedule/', views.schedule, name='schedule'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/tracker/urls.py
from django.contrib import admin
from django.conf.urls import url, include
import accounts.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import *
from accounts import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^updates/', include('updates.urls')),
    #url(r'^devops/', include('devops.urls')),
    url(r'^$', views.loginview, name="login")
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/updates/urls.py
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'updates'

urlpatterns = [
    url(r'^modify/(?P<up_id>[0-9]+)/$', views.process_updates, {}, name='modify'),
    url(r'^process_updates/', views.process_updates, {}, name='process_updates'),
    url(r'^updates_list/', views.updates_list, name='updates_list'),
    url(r'^(?P<up_id>[0-9]+)/$', views.update_view, name="update_view"),
]

tracker/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.contrib.auth import logout


def loginview(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return render(request, 'accounts/home.html')
        else:
            return render(request, 'accounts/login.html', {'error':'Please check the creds'})
    else:
        return render(request, 'accounts/login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return render(request, 'accounts/logout.html')

@login_required
def homeview(request):
    if request.method == 'POST':
        return render(request, 'accounts/home.html')
    else:
        return render(request, 'accounts/home.html')


def forgotview(request):
    return render(request, 'accounts/password_reset_form.html')

@login_required
def usercreatedview(request):
    return render(request, 'accounts/usercreated.html')

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:password_changed')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

@login_required
def password_changed(request):
    return render(request, 'accounts/password_changed.html')

tracker/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<html>
<title>Reset Password!</title>
<style>
.border {
  background-color: #EAF5FB;
  width: 600px;
  border: 10px solid #56B2E4;
  padding: 2px;
  margin: 20px;
  margin-left: 400px;

}
</style>

<form method="post" class="pass">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
{% endblock %}

tracker/accounts/templates/accounts/forgot.html
<!DOCTYPE html>
<html>
<head><title>Forgot Password</title><center>
Password Remainder
</center></head>
<form method="POST" style="text-align:center;" action="{ url 'accounts:forgot' }"><br /><br />

  Mail ID:
    <input type="email" name="email" /><br /><br />

    <input type=submit value='Send mail!' /><br /><br />

<a href="{% url 'accounts:login' %}">Back to login page</a> <br /><br />
</html>

tracker/accounts/templates/accounts/home.html
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #2C9FDD;
  width: 200px;
}

li {
  text-align: center;
  border-bottom: 1px solid #555;
  text-align: center;
}

li a, .dropbtn {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
  background-color: #56B2E4;
}

li.dropdown {
  display: block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #EAF5FB;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: center;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
  display: block;
}
</style>
</head>
<body>
  {% csrf_token %}
<h1 style="color:#4C596B;">AdRoll</h1>
<ul>
  <li><a href="{% url 'updates:updates_list' %}">Process Updates</a></li>
  <li><a href="{% url 'posts:schedule' %}">Engineer Schedule</a></li>
  <li><a href="{% url 'posts:quicklinks' %}">Quick Links</a></li>
  <li class="dropdown">
    <a href="#" class="dropbtn">Non PD alerts</a>
    <div class="dropdown-content">
      <a href="{% url 'posts:tracker_list' %}" >Tracker</a>
      <a href="http://imeasure.iopex.com/posts/pending/?Status=pending">Pending Tickets</a>
      <a href="http://imeasure.iopex.com/posts/unattended/?Resolved_by_Engineer=noc">Unattended Tickets</a>
    </div>
  </li>

</ul>

</body>
</html>

tracker/accounts/templates/accounts/login.html
{% load static %}
{% load staticfiles%}
<head>
<h1><center/>Adroll</h1>
<title>Login</title>
</head>
<form method="POST" style="text-align:center;">
  {% csrf_token %}

  {% if request.GET.next %}
  <input type="hidden" name="next" value={{ request.GET.next }} />
  {% endif %}

Username:<br />
  <input type=text name="username" title="Enter your user name" /> <br />

Password: <br />
  <input type=password name="password" title="Enter your password"/><br /><br />

  <input type=submit value='Login' /><br /><br />
</form>

tracker/accounts/templates/accounts/logout.html
You have been logged out successfully!
<a href="{% url 'login' %}">Login Again?</a>
{% csrf_token %}

tracker/accounts/templates/accounts/password_changed.html
{% extends 'base.html' %}

{% block content %}
<center>
  {% csrf_token %}
  <h1>password changed successfully!<h1>
</center>
{% endblock %}

tracker/accounts/templates/accounts/password_reset_form.html
<!DOCTYPE html>
<html>
<head><title>Forgot Password</title><center>
Password Remainder
</center></head>
<form method="POST" style="text-align:center;" action="{ url 'accounts:forgot' }"><br /><br />
{% csrf_token %}
  Mail ID:
    <input type="email" name="email" /><br /><br />

    <input type=submit value='Send mail!' /><br /><br />

<a href="{% url 'accounts:login' %}">Back to login page</a> <br /><br />
</html>

tracker/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>
<head><title>Sign up!</title></head>
<h1><center>signup</h1>

<form method="POST" style="text-align:center;" action="{ url 'accounts:usercreated' }">
  {% csrf_token %}
Name<br />
<input type=text name="username" /> <br />
Password <br />
<input type=password name="password1" /><br />
Confirm password<br />
<input type=password name="password2" /><br />
<input type=submit value='Signup!' /><br /><br />
<!--<input type=submit value='Login' formaction="{ url 'accounts:login' }">
<p style="color:red;"><a href="/accounts/login">Login</a></p>-->
{% if error %}
{{ error }}
{% endif %}
</form>

tracker/accounts/templates/accounts/usercreated.html
<head><title>Created User</title></head>

<h2>User created successfully<h2>
{% csrf_token %}