tracker/posts/urls.py
from . import views
from django.conf.urls import url
from urllib.parse import unquote
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name = 'posts'

urlpatterns = [
    url(r'^quicklinks/', views.quicklinkview, name='quicklinks'),
    url(r'^tracker_list/', views.tracker_list, name='tracker_list'),
    url(r'^(?P<track_id>[0-9]+)/$', views.tracker_view, name="tracker_view"),
    url(r'^tracker_edit/', views.tracker_edit, {}, name='tracker_edit'),
    url(r'^modify/(?P<track_id>[0-9]+)/$', views.tracker_edit, {}, name='modify'),
    url(r'^search/$', views.search, name='search'),
    url(r'^pending/', views.pending, name='pending'),
    url(r'^unattended/', views.unattended, name='unattended'),
    url(r'^schedule/', views.schedule, name='schedule'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/tracker/urls.py
from django.contrib import admin
from django.conf.urls import url, include
import accounts.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import *
from accounts import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^updates/', include('updates.urls')),
    #url(r'^devops/', include('devops.urls')),
    url(r'^$', views.loginview, name="login")
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/updates/urls.py
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'updates'

urlpatterns = [
    url(r'^modify/(?P<up_id>[0-9]+)/$', views.process_updates, {}, name='modify'),
    url(r'^process_updates/', views.process_updates, {}, name='process_updates'),
    url(r'^updates_list/', views.updates_list, name='updates_list'),
    url(r'^(?P<up_id>[0-9]+)/$', views.update_view, name="update_view"),
]

tracker/updates/models.py
from django.db import models
import datetime
from datetime import date
from datetime import timedelta as tdelta
from django.utils import timezone
# Create your models here.
class Update(models.Model):
    inidate=timezone.now
    Date = models.DateField(null=False, blank=False, default=inidate)
    Topic = models.CharField(max_length=100,null=False)
    From_Engineer = models.CharField(max_length=100,null=False)
    Description = models.TextField(null=True, blank=False)
    Status = models.TextField(null=False, default='Active')

tracker/updates/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
from . import models
from django.utils.safestring import mark_safe
from django.forms import widgets
import datetime
from django.db.models.fields import BLANK_CHOICE_DASH


class UpdateArticle(forms.ModelForm):

    status=[('Active','Active'),('Old','Old')]
    Status = forms.ChoiceField(choices=status, widget=forms.RadioSelect, initial='Active')

    class Meta:
        model = models.Update
        fields = '__all__'
        field_order = ['Date','Topic','From','Description','Status']

tracker/updates/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse, render_to_response
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from . import forms
from .models import Update
from .forms import UpdateArticle
from django.http import HttpResponse
from django.contrib.auth.forms import UserChangeForm
from .tables import UpdateTable
from django_tables2 import RequestConfig
from django_tables2.export.export import TableExport


'''
def process_updates(request):
    if request.method == 'POST':
        updates = forms.UpdateArticle(request.POST)
        if updates.is_valid():
            #save article to db
            updates.save()
            return redirect('updates:updates_list')
    else:
        updates = forms.UpdateArticle()
    return render(request, 'updates/process_updates.html',{'updates':updates})
'''
@login_required
def updates_list(request):
    table = UpdateTable(Update.objects.all(), order_by="-id")
    #filter = AFilter(request.GET, queryset=table)
    RequestConfig(request).configure(table)
    export_format = request.GET.get('_export', None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, table, exclude_columns=('editable','selection'))
        return exporter.response('table.{}'.format(export_format))

    return render(request,'updates/updates_list.html',{'table':table})

@login_required
def update_view(request, up_id):
    #post = Post.objects.get(pk=post_id)
    update = get_object_or_404(Update, pk=up_id)
    return render(request, 'updates/update_view.html', {'update':update})

@login_required
def process_updates(request, up_id=None, template_name='updates/process_updates.html'):
    if up_id is not None:
        update = get_object_or_404(Update, pk=up_id)
    else:
        update = Update()
    updates = UpdateArticle(request.POST or None, instance=update)
    if request.POST and updates.is_valid():
        updates.save()
        redirect_url = reverse('updates:updates_list')
        return redirect(redirect_url)

    return render(request, template_name, {
        'updates': updates
    })

tracker/updates/templates/updates/process_updates.html
<!DOCTYPE html>
<head>
  <title>Process updates</title>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="{% static 'js/toggle.js' %}"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
<script>
        $( function() {
            $( "#id_Date" ).datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true
            });
        });
</script>
  <title>Add new!</title>
</head>

<style>
* {
  box-sizing: border-box;
}

input[type=text], select, textarea {
  width: 300%;
  padding: 4px;
  border: 1px solid #4C596B;
  border-radius: 4px;
  resize: vertical;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
  margin-left: -25px;
}

input[type=submit] {
  background-color: white;
  color: #2C9FDD;
  padding: 3px 10px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: left;
  margin-left : 1%
}

input[type=reset] {
  background-color: white;
  color: #2C9FDD;
  padding: 3px 10px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: left;
  margin-left : 7%
}

input[type=submit]:hover {
  background-color: #4C596B;
}

input[type=reset]:hover {
  background-color: #4C596B;
}

.col-25 {
  float: left;
  width: 15%;
  margin-top: 10px;
}

.col-75 {
  float: left;
  width: 20%;
  margin-top: 22px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

.border {
  background-color: #EAF5FB;
  width: 600px;
  border: 10px solid #56B2E4;
  padding: 2px;
  margin: 20px;
  margin-left : 25%
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .col-25, .col-75, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}

.boxhead a {
    color: #2C9FDD;
    text-decoration: none;
}

.boxhead a:hover{
  background-color: #4C596B;
}

form {
        width: 80%;
        margin-left : 27%
    }

.inlineLabels ul {
  list-style:none;
}

input {
  margin: 0;
  display: inline-block;
}
</style>

<body>
<div class="border">
<form class="site-form" method="post" enctype="multipart/form-data">
  <div class="inlineLabels">
  {% csrf_token %}
  <div class="inline-container">
  {% for field in updates %}
    <div class="row">
        <div class="col-25">
          <b>{{ field.label_tag }}</b>
        </div>
        <div class="col-75">
        </b>{{ field }}</br>
        </div>
    </div>
  {% endfor %}
  </div>
  <div class="boxhead">
    <input type="submit" value="Submit">&nbsp;
      <input type="reset" value="Reset">&nbsp;
    <button><a href="{% url 'updates:updates_list' %}">Back to list</a></button>
  </div>
</form>
</div>
</body>
</html>

tracker/updates/templates/updates/update_view.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block content %}
<html>
<title>View incident</title>
<style>
.buttons {
  background-color: #2C9FDD;
  border-style: solid;
  color: white;
  padding: 7px 12px;
  text-align: center;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}

.buttons:hover {
  background-color: #4C596B;
}

.buttons {
  background-color: #2C9FDD;
  border-style: solid;
  color: white;
  padding: 7px 12px;
  text-align: center;
  display: inline-block;
  font-size: 16px;
  margin: 3px 2px;
  cursor: pointer;
}

.buttons:hover {
  background-color: #4C596B;
}

table {
    border: 1px solid #CCC;
    border-collapse: collapse;
    width: 50%;
    border: none;
    margin-left: 270px;
}

td {
    border: none;
    padding: 15px;
    width: 80px;
    border: none;
}
</style>
<body>
  <div class="container">
<center>
  {% csrf_token %}
<table>
   <tr><td>Date</td> <td>{{ update.Date }}<td></tr>
   <tr><td>Topic</td> <td>{{ update.Topic }}<td></tr>
   <tr><td>From Engineer </td> <td>{{ update.From_Engineer }}<td></tr>
   <tr><td>Description</td> <td>{{ update.Description }}<td></tr>
   <tr><td>Status </td> <td>{{ update.Status }}<td></tr>
</table>
  <form>
    <td><button class="buttons" formaction="{% url 'updates:updates_list' %}">Back to list</button></td>
  <form>
</center>

</div>
</body>
</html>
{% endblock %}

tracker/updates/templates/updates/updates_list.html
{% extends 'base.html' %}

{% block content %}
{% load render_table from django_tables2 %}
{% load django_tables2 %}
{% load bootstrap3 %}
{% load querystring from django_tables2 %}

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Updates</title>
<style>
  th {
    text-align: left;
    background-color: #56B2E4;
    color: #FFFFFF;
    text-decoration: none!important;
    text-align: left;
    padding: 8px;
    font-size: 80%;
  }

  table {
  border-collapse: collapse;
  width: 100%;
  }

  td {
    text-align: left;
    padding: 8px;
    font-size: 80%;
  }

  tr:hover {background-color:#CBE3FA;}

  tr:nth-child(even) {background-color: #F2F9FD;}

  .buttons {
    background-color: #2C9FDD;
    border-style: solid;
    color: white;
    padding: 7px 12px;
    text-align: center;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }

  .buttons:hover {
    background-color: #4C596B;
  }

  div.table-container {
    display: inline-block;
    position:relative;
    overflow:auto;
  }

  input {
  float: right;
  }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
<script language="JavaScript">
function toggle(source) {
    checkboxes = document.getElementsByName('selection');
    for(var i in checkboxes)
        checkboxes[i].checked = source.checked;
}
</script>
{% csrf_token %}
</head>



<body>
 <form>

  <button class="buttons" formaction="{% url 'updates:process_updates' %}">Add New!</button>

  <div class="dropdown">
    <button class="buttons">Export
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% querystring '_export'='csv' %}">Download CSV</a>
      <a href="{% querystring '_export'='xls' %}">Download Excel</a>
      <a href="{% querystring '_export'='json' %}">Download JSON</a>
    </div>
  </div>

  <input id="myInput" type="text" placeholder="Search..">
<div style="background: white;
width: 100%;
height: 100%;
overflow: scroll;
border: 2px solid #2C9FDD;
border-bottom: none;">

<table class="table table-striped">

<tbody  {{ table.attrs.tbody.as_html }} id="myTable">
    {% render_table table %}
</tbody>

</table>
</div>
  </form>
</body>

</html>
{% endblock %}